# Generated by Django 4.0.3 on 2022-04-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tags',
            field=models.CharField(max_length=100),
        ),
    ]
