# Generated by Django 4.0.3 on 2022-04-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0010_alter_categoria_estado_alter_marca_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='afecta',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
