# Generated by Django 4.0.3 on 2022-04-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0012_alter_producto_afecta_alter_producto_formatos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='afecta',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='formatos',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='listapre',
            field=models.BooleanField(default=True),
        ),
    ]
